#Arthur de Castro Dias - 16855302
#Guilherme Cavalcanti de Santana - 15456556

CLASSES = Grafo.java GrafoListaAdjacencia.java GrafoMatrizAdjacencia.java GrafoMatrizAdjacenciaPonderado.java Main.java

all:
	javac $(CLASSES)

run:
	java Main

clean:
	rm -rf *.class